# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-23 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Publication_date',
            new_name='publication_date',
        ),
    ]
