# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-23 17:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_auto_20190923_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=False)),
                ('rented_date', models.DateField(default=datetime.datetime.now)),
                ('available_date', models.DateField(default=datetime.datetime.now)),
                ('book', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('reader', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
