# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-26 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190924_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='format_book',
            field=models.CharField(choices=[('Hardcover', 'Hardcover'), ('Paperback', 'Paperback')], max_length=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[("Kid's Books", "Kid's Books"), ('Politics', 'Politics'), ('Self Help', 'Self Help'), ('Novel', 'Novel')], max_length=15),
        ),
    ]
