# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-26 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190926_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='format_book',
            field=models.CharField(choices=[('Hardcover', 'Hardcover'), ('Paperback', 'Paperback')], max_length=15),
        ),
        migrations.AlterField(
            model_name='book',
            name='store',
            field=models.CharField(choices=[('1', 'Store1'), ('2', 'Store2')], max_length=15),
        ),
    ]
