# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-05 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20190928_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='views',
        ),
    ]
