# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-10 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_number_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
