# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-10 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20191010_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='percentage_rating',
            field=models.IntegerField(default=0),
        ),
    ]
