# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-15 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20191015_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='current_reader',
        ),
    ]
