# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-19 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_auto_20191019_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storebook',
            name='map_store',
            field=models.URLField(default='', max_length=400),
        ),
    ]
