# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-19 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_img',
        ),
    ]
