# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-21 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
