# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-21 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190921_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='test',
            field=models.CharField(default='testdefault', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
