# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-21 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_profile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='default_profile.html', upload_to='images'),
        ),
    ]
