# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-21 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20190921_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='images/default_profile.png', upload_to='images'),
        ),
    ]
