# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-06 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_return_date'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewbook',
            name='reviewed_book',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
    ]
