# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-06 19:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviewbook_reviewed_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewbook',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
