# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-14 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20191010_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewbook',
            name='percentage_score',
            field=models.IntegerField(default=0),
        ),
    ]
