# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-20 21:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_reviewbook_percentage_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewbook',
            name='review_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
