# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-21 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_auto_20191020_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewbook',
            options={'ordering': ('reviewed_book', 'score')},
        ),
        migrations.AlterField(
            model_name='reviewbook',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='reviewbook',
            name='review_title',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='reviewbook',
            name='score',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
