# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-09 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_auto_20191021_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewbook',
            options={'ordering': ('reviewed_book', '-score')},
        ),
    ]
