# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-12 17:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70)),
                ('content', models.TextField()),
                ('contact_date', models.DateField(default=datetime.datetime.now)),
                ('answered', models.BooleanField(default=False)),
            ],
        ),
    ]
