# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-12 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'contact emails'},
        ),
    ]
