# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-15 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191015_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalraised',
            name='number_books',
            field=models.IntegerField(default=0),
        ),
    ]
