# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-19 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20191015_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='link_project',
            field=models.URLField(default='', max_length=400),
        ),
    ]
