# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-21 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_projects_link_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='answered',
        ),
    ]
