# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-22 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20190922_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_by_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_by_phone',
            field=models.BooleanField(default=False),
        ),
    ]
