# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-03 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20190928_1442'),
        ('userprofile', '0005_remove_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favourites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorited_by', to='books.Book'),
        ),
    ]
