# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-03 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_userprofile_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favourites',
            field=models.ManyToManyField(related_name='favorited_by', to='books.Book'),
        ),
    ]
