# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-21 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_userprofile_read_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='books.Book'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='read_books',
            field=models.ManyToManyField(blank=True, to='books.Book'),
        ),
    ]
