# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-09 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_auto_20191022_2215'),
        ('userprofile', '0009_auto_20191021_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_books',
            field=models.ManyToManyField(blank=True, related_name='currently', to='books.Book'),
        ),
    ]
