# Generated by Django 2.2.25 on 2024-08-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_userprofile_current_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_by_email',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_by_phone',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscribe',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
