# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-29 23:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waiting_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitinglist',
            options={},
        ),
        migrations.RemoveField(
            model_name='waitinglist',
            name='date_joined',
        ),
    ]
